<?php
declare(strict_types=1);

namespace MagicalConnection\Database;

use MagicalConnection\Support\MagicalConnectionException;
use wpdb;

/**
 * Provide a database abstraction around WordPress wpdb.
 *
 * Centralizes common database operations used by Magical Connection
 * and provides transaction helpers for database operations that require
 * atomic execution.
 *
 * @since   1.0.0
 * @package CodeArt
 *
 */
class Database
{
    /**
     * WordPress database instance.
     *
     * @since 1.0.0
     */
    private wpdb $wpdb;

    /**
     * Initialize the database service.
     *
     * @since 1.0.0
     *
     * @param wpdb $wpdb WordPress database instance.
     */
    public function __construct(wpdb $wpdb)
    {
        $this->wpdb = $wpdb;
    }

    /**
     * Execute a database query.
     *
     * @since 1.0.0
     *
     * @param string $sql SQL query to execute.
     *
     * @return int|false Number of affected rows or false on failure.
     */
    public function query(string $sql)
    {
        return $this->wpdb->query($sql);
    }

    /**
     * Retrieve multiple database rows as associative arrays.
     *
     * @since 1.0.0
     *
     * @param string $sql SQL query to execute.
     *
     * @return array Query results.
     */
    public function getResults(string $sql): array
    {
        return $this->wpdb->get_results(
            $sql,
            ARRAY_A
        );
    }

    /**
     * Retrieve a single database row as an associative array.
     *
     * @since 1.0.0
     *
     * @param string $sql SQL query to execute.
     *
     * @return array|null Query result or null when no row exists.
     */
    public function getRow(string $sql): ?array
    {
        $result = $this->wpdb->get_row(
            $sql,
            ARRAY_A
        );
        return $result ?: null;
    }

    /**
     * Insert a row into a database table.
     *
     * @since 1.0.0
     *
     * @param string $table              Database table name.
     * @param array $data Data to insert.
     *
     * @return int|false Inserted row ID or false on failure.
     */
    public function insert(string $table, array $data)
    {
        $result = $this->wpdb->insert(
            $table,
            $data
        );

        if ($result === false) {
            return false;
        }

        return $this->wpdb->insert_id;
    }

    /**
     * Update rows in a database table.
     *
     * @since 1.0.0
     *
     * @param string $table               Database table name.
     * @param array $data  Data to update.
     * @param array $where Conditions used to select rows.
     *
     * @return bool True when the query executes successfully.
     */
    public function update(string $table, array $data, array $where): bool
    {
        return $this->wpdb->update($table, $data, $where) !== false;
    }

    /**
     * Delete rows from a database table.
     *
     * @since 1.0.0
     *
     * @param string $table               Database table name.
     * @param array $where Conditions used to select rows.
     *
     * @return bool True when the query executes successfully.
     */
    public function delete(string $table, array $where): bool
    {
        return $this->wpdb->delete($table, $where) !== false;
    }

    /**
     * Get the ID generated by the most recent insert operation.
     *
     * @since 1.0.0
     *
     * @return int Inserted row ID.
     */
    public function insertId(): int
    {
        return $this->wpdb->insert_id;
    }

    /**
     * Prepare a SQL query using WordPress database placeholders.
     *
     * @since 1.0.0
     *
     * @param string $query  SQL query containing placeholders.
     * @param mixed ...$args Values used to replace the placeholders.
     *
     * @return string Prepared SQL query.
     */
    public function prepare(string $query, ...$args): string
    {
        return $this->wpdb->prepare(
            $query,
            ...$args
        );
    }

    /**
     * Start a database transaction.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function beginTransaction(): void
    {
        if ($this->wpdb->query('START TRANSACTION') === false) {
            throw new MagicalConnectionException(
                'Failed to start database transaction.',
                'database_transaction_start_failed'
            );
        }
    }

    /**
     * Commit the current database transaction.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function commit(): void
    {
        if ($this->wpdb->query('COMMIT') === false) {
            throw new MagicalConnectionException(
                'Failed to commit database transaction.',
                'database_transaction_commit_failed'
            );
        }
    }

    /**
     * Roll back the current database transaction.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function rollback(): void
    {
        if ($this->wpdb->query('ROLLBACK') === false) {
            throw new MagicalConnectionException(
                'Failed to rollback database transaction.',
                'database_transaction_rollback_failed'
            );
        }
    }

    /**
     * Get the underlying WordPress database instance.
     *
     * @since 1.0.0
     *
     * @return wpdb WordPress database instance.
     */
    public function wpdb()
    {
        return $this->wpdb;
    }
}